version: "3.8"

services:
  app1:
    build: ./app1
    ports:
      - "5000:5000"
    restart: always

  app2:
    build: ./app2
    ports:
      - "6000:6000"
    depends_on:
      - app1
    restart: always
