name: Model Test

on:
  push:
    branches:
      - main  # Adjust as needed,
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision tqdm pillow numpy torchsummary
        pip install pytest pytest-cov

    - name: Run Model Tests
      working-directory: Session5
      run: |
        python -m pytest test_model.py -v --cov=./ --cov-report=xml

    - name: Upload Coverage Report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: kishkath/ERA3
        file: ./Session5/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
